### ISSUE TITLE
Added wallet-multi-button and got error: "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')"

### ISSUE THREAD

**Issue by leongaban** [lorisleiva/solana-wallets-vue#46] opened 2022-11-01 11:51 UTC
Branch: [](https://github.com/MoonHoldings/MoonHoldings.xyz/tree/dev-leon)

Getting an unknown error

> runtime-core.esm-bundler.js:6560 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js:6560:34)
    at WalletMultiButton.vue:91:24

In our WalletManage.vue 

Imported
```
import { WalletMultiButton } from 'solana-wallets-vue'
import "solana-wallets-vue/styles.css"
```

Then just added the component in the markup like so:
```
<wallet-multi-button></wallet-multi-button>
```

Our main.js
```
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import 'animate.css'

import SolanaWallets from 'solana-wallets-vue'
import 'solana-wallets-vue/styles.css'

import { WalletAdapterNetwork } from "@solana/wallet-adapter-base"

import {
  PhantomWalletAdapter,
  GlowWalletAdapter,
  CoinbaseWalletAdapter,
} from '@solana/wallet-adapter-wallets'

import App from './App.vue'
import router from './router'

const walletOptions = {
  wallets: [
    new PhantomWalletAdapter(),
    new GlowWalletAdapter(),
    new CoinbaseWalletAdapter()
  ],
  autoConnect: true,
}

const app = createApp(App)

app.use(createPinia())
app.use(SolanaWallets, walletOptions)
app.use(router)

app.mount('#app')
```

**Comment by lorisleiva** [comment] 2022-12-09 09:41
Hi there, I think this was to do with a bug in a previous minor version. It should be fixed now so I'll close this but please let me know if the issue is still there and I'll reopen.

**Closed by lorisleiva** 2022-12-09 09:41 UTC
